builds:
  - binary: clitesting
    goos:
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    flags:
      - -mod=vendor

release:
  prerelease: auto

universal_binaries:
  - replace: true

brews:
  -
    name: clitesting
    homepage: https://github.com/Alejandro-Morales/clitesting
    tap:
      owner: Alejandro-Morales
      name: homebrew-Alejandro-Morales
    commit_author:
      name: Alejandro-Morales
      email: alejandro.morales.mad@gmail.com

checksum:
  name_template: 'checksums.txt'